### ISSUE TITLE
 get status with transportID

### ISSUE THREAD

**Issue by amine-damani** [tigron/click-post#1]
Hello, I have made an Web site by using your library, so I would like to say Thank u for making this library.
Now the problem is How to get Status with result information (transportID) by your Library

**Comment by christopheg** [comment]
Hi,
Great to see that this library helped you.
The transportID and submissionID are both variables in the response variable.
I've updated the Readme page to give you an example of such a response.
Hope this helps you!

Regards,
Christophe
